### ISSUE TITLE
There is NO cpcec-20220806 version and zip file in cngsoft can't be compile because uppercase namefiles

### ISSUE THREAD

**Issue by cpcbegin** [cpcitor/cpcec#1]
The latest version is only in http://cngsoft.no-ip.org/cpcec-20220806.zip
But I can't compile in GNU/Linux because all the files have uppercase namefiles.

I solve this renamed to lowercases with this command:

`for original in *; do mv $original `echo $original | tr '[:upper:]' '[:lower:]'`; done`

**Comment by cpcitor** [comment]
Hi @cpcbegin.

Yes, that is one issue with software developed on Windows without attention to other platforms.

I use Linux only so I had the same issue as you.

Also thanks for offering a solution. Here is another.

The script that I wrote which takes archives from the author's site and generates this git history solves this using the `-LL` option of unzip.

From [unzip man page](https://manpages.debian.org/bookworm/unzip/unzip.1.en.html#L):

> Depending on the archiver, files archived under single-case file systems (VMS, old MS-DOS FAT, etc.) may be stored as all-uppercase names; this can be ugly or inconvenient when extracting to a case-preserving file system such as  OS/2  HPFS  or  a case-sensitive one such as under Unix.  By default unzip lists and extracts such filenames exactly as they're stored (excepting truncation, conversion of unsupported characters, etc.); this option causes the names of all files from certain systems to be converted  to  lowercase. The -LL option forces conversion of every filename to lowercase, regardless of the originating file system.

As a consequence, if you get your code by cloning the repository here you don't have the issue. This is one of the reasons why I created this repository.

All in all, this is not an issue with this repository so I believe it is okay to close it. Thanks.
