### ISSUE TITLE
msxec doesn't work in Raspberry pi 400

### ISSUE THREAD

**Issue by cpcbegin** [cpcitor/cpcec#2]
I compile msxec like the other emulators:
`gcc -DSDL2 -O2 -xc msxec.c -lSDL2 -omsxec`
But I can see anything when I run ./msxec from console.
Compile and runs OK in Debian 12 in my PC i7 with 8Gb RAM.

**Comment by cpcbegin** [comment]
I also try to find the bug added lines like this before compiling:
`printf("DEBUG a number!\n");`
And run again.
And I see stop working in these lines of msxec.c file:
`[3898] all_setup(); all_reset();`
....
`[596] while ((k=eval_hex(fgetc(f)))>=0)`

**Comment by cpcitor** [comment]
From cpcec's author at https://www.cpcwiki.eu/forum/emulators/cpcec-a-new-emulator-from-cngsoft/new/#msg_237464

> anyone suffering bugs there can remove the file `msxec.sha` and the only downside will be that cartridge mappers will need to be manually chosen (menu "Edit": Generic 8K, generic 16K, etc) instead of MSXEC checking the list and setting them on its own.

**Comment by cngsoft** [comment]
Can we close this issue? We already found its source months ago (the "unsigned char" default in Raspi400) and solved it.
