### ISSUE TITLE
manic miner tape issue

### ISSUE THREAD

**Issue by 8tpercent** [cpcitor/cpcec#3]
Using the current cpcec  when the loading of  Manic Miner tape finishes, the title screen is skipped and goes straight into the
game... and the major issue being Willy just jumps by himself and the screen/colours are odd.

Tried various CDTs eg.. Manic Miner Software Projects.cdt and all the same issues.

Oddly, if you use the disk version, it's totally fine... eg.  Manic Miner Software Projects.dsk

**Comment by cngsoft** [comment]
As others already said in the CPC Wiki forum, the original tape release relied on the CPC 464 firmware, and failed to run on 664 and 6128 machines with their different system tables. Shall we close this issue?

**Comment by 8tpercent** [comment]
Yes, issue can now be closed. Thank You
